run:
  timeout: 3m       # время выполнения
  tests: true       # проверяем тесты
  concurrency: 4    # параллельно
  cache: true       # кэш для ускорения повторных запусков

linters:
  enable:
    - govet          # базовая проверка кода
    - revive         # стиль и рекомендации
    - gofmt          # форматирование
    - ineffassign    # неиспользуемые присваивания

linters-settings:
  revive:
    ignore-generated-header: true

issues:
  exclude-use-default: false
  exclude-dirs:
    - vendor
    - testdata
